### ISSUE TITLE
Add a tagged version

### ISSUE THREAD

**Issue by hcamacho4200** [nopnop2002/esp-idf-mirf#10]
Could we add a version tag for this repo, even if its 0.0.1.  I am doing some work with this library and would like to pin to a version.

**Comment by nopnop2002** [comment]
Add a TAG when making a revision that breaks compatibility.

As a temporary measure, please fork to your repository.

**Comment by hcamacho4200** [comment]
So you don't want to create a stable version?

**Comment by nopnop2002** [comment]
The current master branch is the stable version.
At the moment, there are no plans to create any other branches.
There have been no major bug fixes in the last four years.

Major version updates to ESP-IDF often result in API changes.
In fact, there were some breaking API changes between ESP-IDF V4 and V5.
This project uses the same API for both ESP-IDF V4 and V5.


If ESP-IDF V6 is released in the future and the API changes catastrophically, there is a possibility that the branch will be separated into a V4V5 compatible version and a V6 compatible version.
