### ISSUE TITLE
Packet loss

### ISSUE THREAD

**Issue by simeondmr** [nopnop2002/esp-idf-mirf#4]
Hello,

I'm using the RF24 with esp32-pico mini and esp32-S3.
The problem is that during the transmission, the receiver loses a lot of packets.
I have also added an 44uF electrolytic capacitor, between 3.3v and GND, but nothing has changed.

**Transmitter example code**

```
....
uint8_t payload = 100;
uint8_t channel = 90;
Nrf24_config(&dev, channel, payload);
...
while (true) {
    if (Nrf24_dataReady(&dev)) {
	    uint8_t pipe = Nrf24_getDataPipe(&dev);
	    Nrf24_getData(&dev, data);
	    ESP_LOGI(pcTaskGetTaskName(0), "Test %d\n", data[0]);
    }
...
}

```

**Receiver example code**

```
...
uint8_t payload = 100;
uint8_t channel = 90;
Nrf24_config(&dev, channel, payload);
...
uint8_t data[100];
memset(data, 29, sizeof(data));
for (int i = 0; i < 10;i++) {
  Nrf24_send(&dev, &data);
  vTaskDelay(10);
}

```

Using this simple code, the receiver receive only 300 bytes instead of 1000.
What could be the problem?

Thanks

Simeon

**Comment by nopnop2002** [comment]
Maximum payload of nRF24L01 is 32 bytes.

**Comment by simeondmr** [comment]
Oh...thanks you!! Sorry for my mistake, you can close the issue.
Now it works correctly.
