### ISSUE TITLE
Transmission keeps failing

### ISSUE THREAD

**Issue by ThynkLabs** [nopnop2002/esp-idf-mirf#6]
![image](https://user-images.githubusercontent.com/114290189/200923394-9baf8fc6-3c3c-4966-8e46-423fbb0ca9ef.png)

I am trying to use Peer to Peer Example on two modules, one with transmitter config and other with receiver config. However, the transmit does not seem to happen. Please help.

**Comment by nopnop2002** [comment]
Incorrect TX_ADDR on the transmit side.

The TX_ADDR on the transmit side must match the RX_ADDR on the receive side.

![nrf24l01_sender](https://user-images.githubusercontent.com/6020549/200969680-2f90f78f-09c0-4d67-ad90-b1e8d21c303c.jpg)
![nrf24l01_receiver](https://user-images.githubusercontent.com/6020549/200969688-e9f0462b-2a27-4268-952c-7c4addffcb1a.jpg)

**Comment by DarshanDodal** [comment]
Hii,
Thanks for quick reply. I changed the address, the receiver is now receiving the data, but at the transmission side there is still a failure message.

Also, I tried the multi receive example at the receiver side with peer to peer code at transmission side, that does not seem to work. Are there any specific changes that I need to make?

**Comment by nopnop2002** [comment]
Try this example on both the sender and receiver sides using two modules.

https://github.com/nopnop2002/esp-idf-mirf/tree/master/Peer-to-peer

**Comment by DarshanDodal** [comment]
Peer to peer code is working, but the transmission side code still logs error but the receiver gets data.

**Comment by nopnop2002** [comment]
Are you using advanced settings?

In normal radio environment, you don't need to use advanced settings when using 2MBps.

I want to know your all settings.

---

When used at long distances, lowering the RF data rate stabilizes it.
When changing the RF data rate, __the sender and receiver must have the same value.__
When using 250KBps, it takes time to PAYLOAD sending and ACK PACKET receiving, so it is necessary to increase the automatic retransmission delay.

**Comment by ThynkLabs** [comment]
### **Settings at Tx side :**

#
# Application Configuration
#
CONFIG_GPIO_RANGE_MAX=33
# CONFIG_RECEIVER is not set
CONFIG_TRANSMITTER=y
# CONFIG_ADVANCED is not set
# end of Application Configuration

#
# nRF24L01 Configuration
#
CONFIG_MISO_GPIO=19
CONFIG_MOSI_GPIO=23
CONFIG_SCLK_GPIO=18
CONFIG_CE_GPIO=4
CONFIG_CSN_GPIO=5
CONFIG_SPI2_HOST=y
# CONFIG_SPI3_HOST is not set
# end of nRF24L01 Configuration


### **Settings at Rx Side:**

#
# Application Configuration
#
CONFIG_GPIO_RANGE_MAX=33
CONFIG_RECEIVER=y
# CONFIG_TRANSMITTER is not set
# CONFIG_ADVANCED is not set
# end of Application Configuration

#
# nRF24L01 Configuration
#
CONFIG_MISO_GPIO=19
CONFIG_MOSI_GPIO=23
CONFIG_SCLK_GPIO=18
CONFIG_CE_GPIO=16
CONFIG_CSN_GPIO=17
CONFIG_SPI2_HOST=y
# CONFIG_SPI3_HOST is not set
# end of nRF24L01 Configuration

**Comment by ThynkLabs** [comment]
I am using it in normal conditions. Here are my settings.

### Settings at Tx Side:
![image](https://user-images.githubusercontent.com/114290189/201470427-0fed7152-61a6-4855-8df3-cf46d50f5586.png)


### Settings at Rx Side:
![image](https://user-images.githubusercontent.com/114290189/201470369-e922c991-210f-4073-8874-9f0e455841ba.png)

**Comment by nopnop2002** [comment]
I don't know why.
Try swapping the sending module and the receiving module.

Be sure to turn off the power once.

**Comment by DarshanDodal** [comment]
Tried everything. I guess the transmitter is not receiving an ACK after transmission. 


Btw, I want to use the Multi Receiver code at receiver side. So is it possible to use the peer to peer code at tx side?

**Comment by nopnop2002** [comment]
>Tried everything. I guess the transmitter is not receiving an ACK after transmission.


I think so.


>Btw, I want to use the Multi Receiver code at receiver side. So is it possible to use the peer to peer code at tx side?


Multi-receive uses the following receiving addresses.
1RECV
2RECV
3RECV
4RECV
5RECV

The sender must send to this address.

**Comment by DarshanDodal** [comment]
> Multi-receive uses the following receiving addresses.
> 1RECV
> 2RECV
> 3RECV
> 4RECV
> 5RECV
> 
> The sender must send to this address.
> 
Yes. I tried changing the address in Tx accordingly. That does not seem to work.

**Comment by nopnop2002** [comment]
On the transmit side only, try powering the nRF24L01 with an external power supply.

I use the AMS1117 to convert the board's 5V output to 3.3V and feed it to the nRF24L01.
![ExternalPowerSoure](https://user-images.githubusercontent.com/6020549/201508019-e257ad6e-b2d2-4fc1-afc5-140f24064d91.JPG)

---

I have several nRF24L01 modules.
One of them always causes a transmission error.
It's probably a hardware problem.

**Comment by nopnop2002** [comment]
Multi-receive uses the following receiving addresses.
1RECV
2RECV
3RECV
4RECV
5RECV

It is necessary to match not only the address but also the payload size to be sent and received.

https://github.com/nopnop2002/esp-idf-mirf/blob/master/Multiple-Receive/main/main.c#L19


Added sender example to here.
https://github.com/nopnop2002/esp-idf-mirf/tree/master/Multiple-Receive

**Comment by ThynkLabs** [comment]
Thanks a lot for making changes.
However, I am still not able to make the Multi Receiver example work.
![image](https://user-images.githubusercontent.com/114290189/201523335-c14dbe74-656d-496c-b644-1ab05929b81e.png)

**Comment by nopnop2002** [comment]
I changed the component.

Logs the failure reason when a send fails.

If "Status register timeout", it may be a hardware issue

![nrf24l01-bad-modue](https://user-images.githubusercontent.com/6020549/201545976-c3a2fe83-36a6-48b9-a825-5cf5a0699014.jpg)

**Comment by ThynkLabs** [comment]
I tried the example. This is what it logs.

![ss temp (2)](https://user-images.githubusercontent.com/114290189/201877853-aa73611b-d9de-4cb2-88a4-15d6e02b5fef.png)

**Comment by nopnop2002** [comment]
The transmitter did not receive an ACK after sending.

Also

Recipient does not return ACK after receiving


I don't know which one, but there is no doubt that it is abnormal.

It is difficult to pursue further.

**Comment by ThynkLabs** [comment]
Is it working on your hardware?

**Comment by nopnop2002** [comment]
![mirf-sender](https://user-images.githubusercontent.com/6020549/201916201-dac3a621-7095-4179-8dee-715ac6947ce5.jpg)

**Comment by ThynkLabs** [comment]
I checked the modules closely, on one module NRF24L01+ is used, and a chinese clone Si24R1 is used on another module. I am not sure if that is causing the issue.

**Comment by nopnop2002** [comment]
About Si24R1 

https://forum.arduino.cc/t/si24r1-vs-nrf24l01-working-distance-difference/313158/2
