### ISSUE TITLE
Init with SPI not driven by menuconfig

### ISSUE THREAD

**Issue by hcamacho4200** [nopnop2002/esp-idf-mirf#9]
I am thinking it would be nice to be able to init the library without having to use menuconfig, taking configuration from the build system, and have that contained within the source code of the caller.

Looking for opinions on this before I create a PR.

HFC

**Comment by nopnop2002** [comment]
If you create sdkconfig.defaults, there is no need to do memuconfig.

You can initialize the library without using menuconfig.

https://docs.espressif.com/projects/esp-idf/en/stable/esp32/api-reference/kconfig.html
